### PR TITLE
adding my own spammers to the list

### PR DESCRIPTION
**Pull request by JasonD94**
Love this repo. I've got about ~30 emails that I've blacklisted myself. Looks like 7 of those were already here, so I added the other 23.

I couldn't seem to get the genfilter bash file working on Windows as well. I installed Ubuntu with the "Windows Subsystem for Linux" (WSL) enabled, and changed the line endings to Unix style but running the script doesn't seem to update the mailFilters.xml file. Maybe I need to fire up a Linux VM and try it natively though. For my own email system on ZOHO, I just need the list.txt file to import as blacklisted domains so just a heads up for the gmail users.

### CODE REVIEW

**Review by jceloria — COMMENTED** [review]
I wanted to minimize the number of files that need to be modified for every entry, if I add one domain or email address, now that needs to be added to 2 other files. 

I can generate a CSV in the genfilter.* scripts I've recently modified (I just added a Powershell script as well) if that's something you would be interested in? 

I hadn't really considered any other mail filtering formats until now, it might be worth taking a look at though.

**Review by jceloria — APPROVED** [review]

**Comment by jceloria** [comment]
> Love this repo. I've got about ~30 emails that I've blacklisted myself. Looks like 7 of those were already here, so I added the other 23.
> 
> I couldn't seem to get the genfilter bash file working on Windows as well. I installed Ubuntu with the "Windows Subsystem for Linux" (WSL) enabled, and changed the line endings to Unix style but running the script doesn't seem to update the mailFilters.xml file. Maybe I need to fire up a Linux VM and try it natively though. For my own email system on ZOHO, I just need the list.txt file to import as blacklisted domains so just a heads up for the gmail users.

Originally it would just write out to the screen that then you would redirect the output to the file (I've been checking in the mailFilters.xml after each edit). I've since updated the script to write out to the screen as well as the file. I've also added a Powershell script (only tested with docker powershell at the moment) for those that do not have bash readily available. 

If you could test that out and give me feedback, that would be awesome if it was a bit easier to use for you.

**Comment by JasonD94** [comment]
Oh my bad - I thought adding the CSV files would stick to my fork, I forgot pull requests show everything. I can go back and remove the CSV files and add that to a branch instead.

**Comment by JasonD94** [comment]
Actually I see you've merged it already. I'll give those new scripts a shot!

**Comment by jceloria** [comment]
> Oh my bad - I thought adding the CSV files would stick to my fork, I forgot pull requests show everything. I can go back and remove the CSV files and add that to a branch instead.

I'm all for adding other formats, I myself have been trying to ween myself off of Gmail for awhile.

**Review by jceloria — APPROVED** [review]

**Comment by JasonD94** [comment]
> I can generate a CSV in the genfilter.* scripts I've recently modified (I just added a Powershell script as well) if that's something you would be interested in?

I just ran them, looks like they work well for the xml gmail file. I didn't see any CSV file options though. How would you do that? Or did you mean you could add that - I'm happy to as well.

**Comment by JasonD94** [comment]
I added a powershell function to generate CSV files on one of my branches:

https://github.com/JasonD94/recruiter-spam/blob/csv_file_generation/genfilter.ps1

Seems to work pretty well for now.

**Comment by jceloria** [comment]
Yeah, sorry... I haven't added the CSV bit yet, but I'm working on it now.

**Comment by jceloria** [comment]
I just pushed the changes with help output in the README, let me know if
there's any issues or if something doesn't look right.

**Comment by jceloria** [comment]
LOL I just saw this, that could have saved me some time.

**Comment by JasonD94** [comment]
Ah shoot my bad - I thought about making a new PR to show it off, but wasn't sure what you were working on ha. I'll check out the latest stuff now!

**Comment by JasonD94** [comment]
Ah I like how you did it! much cleaner than my hacky solution, but I just wanted something that works for when I find new spammers.

**Comment by jceloria** [comment]
I used these last changes as excuses to learn more about powershell, this
whole thing started because of the same reason, I was actually generating
one big filter with all of the domains and then hit a limit with Gmail. I
hadn't considered other filters until you mentioned it. The more people
that contribute, the less garbage we have to wade through.

Thanks for your contribution btw.

**Comment by JasonD94** [comment]
Np. I've got my LinkedIn/Indeed/probably other job boards updated with my resume, and it contains my email so it seems like the amount of spam I get has gone up 10x in the last month since I updated everything. Was happy to stumble across this and got a few more emails to add to the list it seems since the spam never stops coming.

I added issue #3 - I think the Powershell script could use a description, just a bit confusing to me using it the first time until I looked through it closer. Also learned that Get-Help is a thing - never knew about that in Windows.

I use Zoho as well for my custom email, I could certainly use the gmail filters too since I forward everything over but making a CSV file is the easiest way I've found to import things in ZOHO. Wouldn't hurt to add the same ones in gmail though to block anything that comes directly to one of my @gmail.com emails though...

**Pull request merged**
